/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.byohttp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App app = new App();
        assertNotNull("app should have a greeting", app.getGreeting());
    }

    @Test public void testDivide() {
        App app = new App();
        assertEquals("result should be 2", 2.0, app.divide(6.0, 3.0), 0.0);
    }

    @Test(expected = RuntimeException.class)
    public void testDivideByZero() {
        App app = new App();
        app.divide(6.0, 0.0);
    }
}
