/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.byohttp;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

public class ByoHttpTest {

    @Test
    @DisplayName("When constructing ByoHttp given port and resources path then return a new instance")
    public void testApp() {
        ByoHttp app = new ByoHttp(1234, "/var/www");
        // no exception thrown
    }


}
