/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.byohttp;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public double divide(double a, double b) {
        if (b == 0) {
            throw new RuntimeException("Can't divide by zero");
        }

        return a / b;
    }

    public static void main(String[] args) {
        for (String arg : args) {
            System.out.println(arg);
        }
        
        System.out.println(new App().getGreeting());
    }
}
